server:
  port: 10010
spring:
  application:
    name: fzc-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /friday # \u8DEF\u7531\u8DEF\u5F84\u524D\u7F00
  routes:
    fzc-user: /user/** # \u7528\u6237\u5FAE\u670D\u52A1\u7684\u6620\u5C04\u8DEF\u5F84
    fzc-stock-us: /us/** # \u8D26\u5355\u5FAE\u670D\u52A1\u6620\u5C04\u8DEF\u5F84
    fzc-stock: /stock/** #\u57FA\u91D1\u4E0E\u80A1\u7968\u5FAE\u670D\u52A1
    fzc-futu: /futu/** #\u56FA\u5B9A\u8D44\u4EA7\u4E0E\u503A\u52A1
