server:
  port: 8089


# xxl-job
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8899/xxl-job-admin # ????????? [??]???????????????????????????????????"???????"?"??????"???????????
    executor:
      address: #empety
      appname: fzc-us-a # ??? AppName [??]??????????????????????
      ip: # ???IP [??]???????????IP????????????IP??IP????Host?????????????? "?????" ? "???????????"?
      port: 6665 # ### ?????? [??]?????0???????????9999?????????????????????????
      logpath: /data/applogs/xxl-job/jobhandler # ??????????????? [??] ????????????????????????
      logretentiondays: 30 # ??????????? [??] ? ????????, ???????3???; ??, ?-1, ?????????
    accessToken:   # ?????TOKEN [??]???????


spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
      config:
        server-addr: http://localhost:8848
        file-extension: yaml

  # ?? RedisProperties ?
  redis:
    lettuce:
      pool:
        max-active: 8 # ????????
        max-idle: 8 # ??????????
        min-idle: 0 # ??????????
        max-wait: -1ms # ????????????????????
    host: 127.0.0.1
    port: 6379
    #    password: # Redis ???????????????????? Redis ???
    database: 0 # Redis ???????? 0 ?
    timeout: 30000ms # Redis ?????????????
    # ?? RedissonProperties ?
  #    redisson:
  #      config: classpath:redisson.yml # ?????????? org.redisson.config.Config ??

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      auto-index-creation: true
      host: localhost # mongodb\u7684\u8FDE\u63A5\u5730\u5740
      port: 27017 # mongodb\u7684\u8FDE\u63A5\u7AEF\u53E3\u53F7
      database: StockAnalysisSystem # mongodb\u7684\u8FDE\u63A5\u7684\u6570\u636E\u5E93
          #      uri: mongodb://flamenco:123456@120.77.182.105:27017/flamenco?main?authSource=admin&authMechanism=SCRAM-SHA-1
#      mongo2:
#        uri: mongodb://127.0.0.1:27017/SasCache
#        auto-index-creation: true
#        host: localhost # mongodb\u7684\u8FDE\u63A5\u5730\u5740
#        port: 27017 # mongodb\u7684\u8FDE\u63A5\u7AEF\u53E3\u53F7
#        database: StockAnalysisSystem # mongodb\u7684\u8FDE\u63A5\u7684\u6570\u636E\u5E93
          #      uri: mongodb://flamenco:123456@120.77.182.105:27017/flamenco?main?authSource=admin&authMechanism=SCRAM-SHA-1


  application:
    name: fzc-stock-a
  datasource:
    url: jdbc:mysql:///flamenco?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    #    type: com.alibaba.druid.pool.DruidDataSource # ????? DruidDataSource
    #      # Druid ???????? DruidDataSource ?? setting ?????
    #      druid:
    #        min-idle: 0 # ???????????????? 0 ??
    #        max-active: 20 # ??????????????????????? 8 ??
    #        filter:
    #          stat: # ?? StatFilter ????? https://github.com/alibaba/druid/wiki/%E9%85%8D%E7%BD%AE_StatFilter
    #            log-slow-sql: true # ???????
    #            slow-sql-millis: 5000 # ? SQL ?????????
    hikari:
      max-lifetime: 288300
      maximum-pool-size: 9


#  devtools:
#    restart:
#      enabled: true
#      additional-paths: src/java/main
#      additional-exclude: static/**,public/**,WEB-INF/**




#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
#  instance:
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 15

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  typeAliasesPackage: com.fzc.fzcstocka.model
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
arthas:
  agent-id: fzc-a-Stock

redis:
  database: fzc
  key:
    stockName: 'fzc:stockAName'
    StockDescription: 'fzc:stockDescription'
    admin: 'fzc:stockUs'
    resourceList: 'fzc:resourceList'
  expire:
    common: 86400 # 24??