server:
  port: 8086

shiro:
  loginUrl:
  unauthorizedUrl:

spring:
  redis:
    lettuce:
      pool:
        max-active: 8 # ????????
        max-idle: 8 # ??????????
        min-idle: 0 # ??????????
        max-wait: -1ms # ????????????????????
    host: 127.0.0.1
    port: 6379
    #    password: # Redis ???????????????????? Redis ???
    database: 0 # Redis ???????? 0 ?
    timeout: 30000ms # Redis ?????????????
    # ?? RedissonProperties ?
    #    redisson:
    #      config: classpath:redisson.yml # ?????????? org.redisson.config.Config ??
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      auto-index-creation: true
      host: localhost # mongodb\u7684\u8FDE\u63A5\u5730\u5740
      port: 27017 # mongodb\u7684\u8FDE\u63A5\u7AEF\u53E3\u53F7
      database: flamenco # mongodb\u7684\u8FDE\u63A5\u7684\u6570\u636E\u5E93
  #      uri: mongodb://flamenco:123456@120.77.182.105:27017/flamenco?main?authSource=admin&authMechanism=SCRAM-SHA-1

  application:
    name: fzc-user-shiro
  datasource:
    url: jdbc:mysql:///flamenco?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      max-lifetime: 288300
      maximum-pool-size: 9
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
#  instance:
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 15

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  typeAliasesPackage: com.fzc.fzcusershiro.model
  global-config:
    db-config:
      id-type: auto
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true